const express = require('express')
const router = express.Router()
const { addProject, getProjects, getProjectById, modifyProject, deleteProject, allUserProjects, addMember } = require('../controllers/projet.controller')
const protect = require('../middlewares/protect')
const taskRouter = require('../routes/tasks.route')
router.use('/:projectId/tasks', taskRouter)
router.get('/', allUserProjects)
router.get('/all',protect, getProjects)
router.get('/:id',protect, getProjectById)
router.post('/',protect, addProject) 
router.put('/:projectId/members',protect, addMember)
router.put('/:id',protect, modifyProject)
router.delete('/:id',protect, deleteProject)

module.exports = router