const express = require('express')
const router = express.Router()
const { addProject, getProjects, getProjectById, modifyProject, deleteProject, allUserProjects, addMember, getMembers } = require('../controllers/projet.controller')
const protect = require('../middlewares/protect')
const taskRouter = require('../routes/tasks.route')
const checkPermission = require('../middlewares/checkPermission')
router.use('/:projectId/tasks', taskRouter)
router.get('/', allUserProjects)
router.get('/all', protect, getProjects)
router.get('/:id', protect, getProjectById)
router.get('/:id/members', protect, getMembers)
router.post('/', protect, addProject)
router.post('/:projectId/members', protect, addMember)
router.put('/:id', protect, modifyProject)
router.delete('/:id', protect, deleteProject)

module.exports = router